from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    FarmViewSet,
    DeviceViewSet,
    SensorReadingViewSet,
    ThresholdViewSet,
    AlertViewSet,
    DeviceCommandViewSet,
    sensor_data_ingest,
    overview,
    monitoring,
    irrigation,
)


router = DefaultRouter()
router.register(r"farms", FarmViewSet, basename="farm")
router.register(r"devices", DeviceViewSet, basename="device")
router.register(r"readings", SensorReadingViewSet, basename="reading")
router.register(r"thresholds", ThresholdViewSet, basename="threshold")
router.register(r"alerts", AlertViewSet, basename="alert")
router.register(r"commands", DeviceCommandViewSet, basename="command")


urlpatterns = [
    # IoT ingestion (ESP32)
    path("sensor-data/", sensor_data_ingest, name="sensor-data"),

    # Frontend helpers
    path("overview/", overview, name="overview"),
    path("monitoring/", monitoring, name="monitoring"),
    path("irrigation/", irrigation, name="irrigation"),

    # CRUD routes (auto-generated by the router)
    path("", include(router.urls)),
]