# Generated by Django 5.2.6 on 2026-09-20 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=150)),
                ('location_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('size_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(db_column='farm_id', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='agri.farm')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('light_level', models.PositiveIntegerField(blank=True, null=True)),
                ('rain_detected', models.BooleanField(default=False)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('smoke_level', models.PositiveIntegerField(blank=True, null=True)),
                ('flame_detected', models.BooleanField(default=False)),
                ('motion_detected', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agri.device')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_min', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('moisture_max', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('pump_on_threshold', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('frost_temp_alert_c', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('storm_pressure_drop_hpa', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='agri.device')),
            ],
            options={
                'verbose_name': 'Threshold',
                'verbose_name_plural': 'Thresholds',
                'db_table': 'thresholds',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('intrusion', 'Intrusion'), ('frost', 'Frost'), ('storm', 'Storm'), ('threshold_breach', 'Threshold Breach'), ('low_battery', 'Low Battery'), ('sensor_error', 'Sensor Error')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agri.device')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device'], name='alerts_device__6f1c01_idx'), models.Index(fields=['is_resolved', 'created_at'], name='alerts_is_reso_80152e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('PUMP_ON', 'Pump On'), ('PUMP_OFF', 'Pump Off'), ('REBOOT', 'Reboot'), ('OTA_UPDATE', 'OTA Update')], max_length=20)),
                ('source', models.CharField(choices=[('automation', 'Automation'), ('manual', 'Manual')], default='automation', max_length=15)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agri.device')),
                ('issued_by', models.ForeignKey(blank=True, db_column='issued_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Command',
                'verbose_name_plural': 'Device Commands',
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='device_comm_device__46d6a1_idx'), models.Index(fields=['device', 'command', 'created_at'], name='device_comm_device__fca7ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farmer'], name='farms_user_id_ce06ee_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['farm'], name='devices_farm_id_b4432f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'recorded_at'], name='sensor_read_device__a116dc_idx'),
        ),
    ]
