# Generated by Django 5.2.6 on 2026-09-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_farm_status_farm_farms_status_ea41ba_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='service_notes',
            field=models.TextField(blank=True, help_text='Instructions or notes for the assigned technician.', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='service_requested',
            field=models.BooleanField(default=False, help_text='Set to true when this farm needs a technician visit.'),
        ),
        migrations.AddField(
            model_name='farm',
            name='technician',
            field=models.ForeignKey(blank=True, db_column='technician_id', help_text='Technician responsible for installing/maintaining devices on this farm.', limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['technician'], name='farms_technic_d8749f_idx'),
        ),
    ]
