# Generated by Django 5.2.6 on 2026-09-24 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_farm_service_notes_farm_service_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer_feedback',
            field=models.TextField(blank=True, help_text="Farmer's feedback once the technician has completed the job.", null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer_satisfied',
            field=models.BooleanField(blank=True, help_text='True if farmer confirmed the work, False if it needs redoing. Null while pending.', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='service_status',
            field=models.CharField(choices=[('none', 'No service needed'), ('requested', 'Requested by farmer'), ('assigned', 'Technician assigned'), ('completed', 'Awaiting farmer feedback'), ('confirmed', 'Confirmed by farmer')], default='none', help_text='Current state of the service workflow.', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='service_requested',
            field=models.BooleanField(default=False, help_text='Derived from service_status; True whenever service is active or awaiting feedback.'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['service_status'], name='farms_service_d11a63_idx'),
        ),
    ]
