# Generated by Django 5.2.6 on 2026-09-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('farmers', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('technician', 'Technician'), ('admin', 'Admin')], default='farmer', help_text='Business role: farmer, technician, or admin.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['role'], name='farmers_role_af92f1_idx'),
        ),
    ]
